PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"
BOS_TOKEN = "<BOS>"
EOS_TOKEN = "<EOS>"

DEFAULT_SPECIAL_TOKENS: tuple[str, ...] = (PAD_TOKEN, UNK_TOKEN, BOS_TOKEN, EOS_TOKEN)

DEFAULT_VOCAB_SIZE = 256
DEFAULT_EMBEDDING_DIM = 64
DEFAULT_NUM_REFERENCES = 256
DEFAULT_MATCHER_EPS = 1e-8
